"""
run_analysis.py
Task 1.3 runner — generates the Week 1 analysis report from existing metric CSVs.

Place at:  ~/research/Mask2Former/scripts/run_analysis.py   (overwrites the placeholder)
Run from:  ~/research/Mask2Former/

Usage:
    python scripts/run_analysis.py

Expects these files to already exist (generated by run_stability_metrics.py):
    experiments/stability_analysis/results/cityscapes_entropy.csv
    experiments/stability_analysis/results/jsd_cs_to_bdd.csv
    experiments/stability_analysis/results/jsd_cs_to_mapillary.csv

Output:
    experiments/stability_analysis/reports/week1_analysis.md
"""

import logging
import os
import sys

sys.path.insert(0, os.path.abspath("."))
sys.path.insert(0, os.path.join(os.path.abspath("."), "mask2former"))

from mask2former.analysis.analyzer import run_analysis

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)

RESULTS_DIR = "experiments/stability_analysis/results"
REPORT_DIR  = "experiments/stability_analysis/reports"


def main():
    logger.info("=" * 60)
    logger.info(" WEEK 1 ANALYSIS REPORT")
    logger.info("=" * 60)

    # Verify inputs exist
    required = [
        "cityscapes_entropy.csv",
        "jsd_cs_to_bdd.csv",
        "jsd_cs_to_mapillary.csv",
    ]
    for fname in required:
        path = os.path.join(RESULTS_DIR, fname)
        if not os.path.exists(path):
            logger.error(f"Missing: {path}")
            logger.error("Run run_stability_metrics.py first (single + cross modes).")
            sys.exit(1)
        logger.info(f"  ✓ {path}")

    # Generate
    report_path = run_analysis(RESULTS_DIR, REPORT_DIR)

    logger.info("=" * 60)
    logger.info(f" Report saved: {report_path}")
    logger.info(" Phase 1 complete. Milestone 1 checkpoint reached.")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()